DEVprogramming-Team4/PROMENTOUS

client/src/styles/ih_kim.css

부트스트랩의css 를건드려 버려서 css 변경합니다 

---

client/src/router/index.js
client/src/views/ReviewDetailView.vue

- UI만 임시로 만들어놨습니다. (+ 라우터 연결)
- 백엔드 API 개발하면서 데이터 연결작업도 그 때 같이 할 예정입니다.

Feat: 프로젝트 후기 상세 화면 추가

---

client/src/views/ProjectDetailView.vue

* 프로젝트 상세 화면 API 연동 개발중
(우측 바, 모집인원, 댓글 부분 미완성)

Feat: 프로젝트 상세 화면 API 연동

---

client/src/components/linkRegister.vue

Feat: 링크 등록 컴포넌트

---

client/src/components/CommentView.vue
client/src/components/WriteCommentView.vue
client/src/components/WriteRecommentView.vue
client/src/styles/yuri.css
client/src/views/ProjectDetailView.vue
client/src/views/ReviewDetailView.vue

* 대댓글 작성 UI 개발
* 댓글 등록 axios post 함수 작성(데이터 연결은 미완성입니다.)

Feat: 댓글 UI 개선 + post 함수 작성

---

client/package-lock.json
client/package.json
client/src/components/TextEditor.vue
client/src/main.js
client/src/views/HomeView.vue
client/src/views/ProjectRecruitView.vue
client/src/views/RecruitWriteView.vue
client/src/views/TeamManageView.vue

작성페이지(변수미설정) 텍스트 에디터 추가 외 디자인 수정.

Feat WritePage , TextEditor

---

client/package-lock.json
client/package.json
client/src/components/CardList.vue
client/src/components/GoogleLogin.vue
client/src/components/layouts/HeaderLayout.vue
client/src/main.js
client/src/mixins/index.js
client/src/store/index.js

로그인 기능 및 프로젝트 조회 기능

---

client/src/views/TeamManageView.vue

feat   팀관리화면

---

client/src/components/CardList.vue
client/src/components/GoogleLogin.vue
client/src/components/layouts/HeaderLayout.vue
client/src/components/layouts/PaginationLayout.vue
client/src/components/layouts/RecruitStatus.vue
client/src/components/layouts/RegionSortLayout.vue
client/src/components/layouts/StackSearchLayout.vue
client/src/views/ProjectRecruitView.vue
client/src/views/RecruitWriteView.vue

- RecruitWriteView.vue 파일에 서버로 전송할 데이터를 주석으로 1차 정리해두었습니다.
- 로그인 시 Vuex에 담기는 값을 변경했습니다. 필요한 페이지에선, 콘솔에서 확인해보시면 좋을 것 같습니다.
- 기존 CardList.vue에서 호출하고 받던 응답을 부모요소(ProjectRecrutView.vue)에서 호출하고 props로 넘기는 방식으로 전환했습니다.
- 위의 변경에 따라, 메인페이지에서도 부모에서 호출하고 props로 넘겨주어야 합니다.

0717 곽성재 금주 작업

---

client/src/components/CardList.vue
client/src/components/GoogleLogin.vue
client/src/components/layouts/HeaderLayout.vue
client/src/views/ProjectRecruitView.vue

* fix:로그인시 특정메뉴에서 있던 라우팅 오류 해결
* fix:사용스택 렌더링 해결
* fix:로그인시 유저이미지 꺠짐 해결
* feat:로그인유저에게만 모집 글 작성 버튼 렌더링

0720 곽성재 커밋사항

---

client/src/views/ProjectDetailView.vue
client/src/views/TeamManageView.vue

feat 멤버정보 가져오기api추가 [getCurrentMembers]

feat 멤버정보 가져오기api추가 [getCurrentMembers]

---

client/src/components/CardList.vue
client/src/components/layouts/HeaderLayout.vue
client/src/components/layouts/RegionSortLayout.vue
client/src/views/RecruitWriteView.vue

* feat:조회수데이터 기능 추가
* feat:비로그인시 멘토링 메뉴숨김처리
* feat:지역 구분 데이터 라벨링 및 disable처리
* feat: 모집글 작성기능 구현

0720 (수) 곽성재 작업분량입니다.

---

client/src/views/TeamManageView.vue

fix 팀관리페이지

---

client/src/components/CardList.vue
client/src/components/SearchAll.vue
client/src/components/layouts/HeaderLayout.vue
client/src/views/ProjectRecruitView.vue

1. 검색기능: 제목, 작성자, 내용 기준으로 검색가능 및 backspace로 input값이 비워지면 다시 요청을 보냄(데모버전)
2. 로그아웃 시 '/home'으로 라우팅 처리
3. 모집게시판 페이지 네이션 스타일변경
4. 카드리스트 스타일 변경(모집완료 카드는 블러처리, 프로필 사진 크기조정, ON OFF 로 렌더링 되는 문구 처리완료)

0725 곽성재 작업 사항

---

client/src/components/CardList.vue
client/src/components/layouts/StackSearchLayout.vue

StackSearch에서 다중 검색이 안되다 보니 단일검색에 맞추어 디자인 변경했습니다.

0727 곽성재 작업사항

---

client/src/views/TeamManageView.vue

feat .팀관리 Smooth오픈

---

client/src/views/HomeView.vue

1. 프로젝트 리스트 REC >> 모집중 등의 처리 
2. 프로젝트 리스트 시작예정일 substring
3. 멘토리스트 관심 분야 한글처리

Feat: 메인페이지 마무리

---

client/src/components/DetailPageProfileModal.vue
client/src/components/UserProfileModal.vue
client/src/components/applicantProfileModal.vue
client/src/components/layouts/PartSearchLayout.vue
client/src/components/layouts/StackSearchLayout.vue
client/src/views/HomeView.vue
client/src/views/MyPageView.vue
client/src/views/TeamManageView.vue

feat 프로필모달 연결, 분야,언어 검색컴포넌트 메소드추가, 마이페이지, 팀관리 수정, HomeView 멘토리스트 디자인

feat 프로필모달 연결, 분야,언어 검색컴포넌트 메소드추가, 마이페이지, 팀관리 수정, HomeView 멘토리스트 디자인

---

client/src/components/layouts/StackSearchLayout.vue
client/src/views/HomeView.vue
client/src/views/MentorDetailView.vue
client/src/views/MyPageView.vue

1. 마이페이지 / 메인페이지 라우팅 처리 및 스크롤 처리

Feat: 220731 안요한

---

client/src/views/MentorDetailView.vue

Feat: 멘토디테일
